# Generated by Django 5.1.5 on 2025-03-03 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
            preserve_default=False,
        ),
    ]
